import turtle

#Author: Mai Huu Nghia

turtle.Screen().bgcolor("#142D65")

t = turtle.Turtle()
t.speed(10)
t.pensize(10)
t.penup()

def draw_hcmut1 () :
    t.setposition(0,301)
    t.pendown()
    t.begin_fill()
    t.color('white')
    t.pencolor("white")
    t.right(150)
    t.forward(172)
    t.left(60)
    t.forward(172)
    t.right(60)
    t.forward(172)
    t.left(60)
    t.forward(172)
    t.left(60)
    t.forward(172)
    t.left(60)
    t.forward(172)
    t.right(60)
    t.forward(172)
    t.left(60)
    t.forward(172)
    t.left(60)
    t.forward(172)
    t.left(60)
    t.forward(172)
    t.right(60)
    t.forward(172)
    t.left(60)
    t.forward(172)
    t.end_fill()
    t.penup()
#Author: Mai Huu Nghia
def draw_hcmut2 () :
    t.setposition(0,280)
    t.pendown()
    t.begin_fill()
    t.color('#042B92')
    #t.pencolor("black")
    t.left(60)
    t.forward(150)
    t.left(60)
    t.forward(172)
    t.right(60)
    t.forward(172)
    t.left(60)
    t.forward(154)
    t.left(60)
    t.forward(150)
    t.left(60)
    t.forward(172)
    t.right(60)
    t.forward(172)
    t.left(60)
    t.forward(150)
    t.left(60)
    t.forward(154)
    t.left(60)
    t.forward(172)
    t.right(60)
    t.forward(172)
    t.left(60)
    t.forward(150)
    t.end_fill()
    t.penup()
#Author: Mai Huu Nghia
def draw_hcmut3 () :
    t.pendown()
    t.backward(5)
    t.begin_fill()
    t.color('#1488DB')
    #t.pencolor("black")
    t.left(120)
    t.forward(164)
    t.left(60)
    t.forward(145)
    t.left(120)
    t.forward(164)
    t.left(60)
    t.forward(145)
    t.end_fill()
    t.penup()
    t.left(120)
    t.forward(329)
    t.left(90)
    t.backward(2)
    t.right(30)
    t.forward(151)
    t.pendown()
    t.begin_fill()
    t.color('#1488DB')
    t.forward(164)
    t.right(120)
    t.forward(146)
    t.right(60)
    t.forward(164)
    t.right(120)
    t.forward(145)
    t.end_fill()
    t.penup()
#Author: Mai Huu Nghia
def draw_hcmut4():
    t.setposition(-134,32)
    t.pendown()
    t.begin_fill()
    t.color("#1488DB")
    t.pensize (10)
    t.pencolor("#1488DB")
    t.right(120)
    t.forward(149)
    t.right(60)
    t.forward(167)
    t.right(120)
    t.forward(150)
    t.right(60)
    t.forward(167)
    t.end_fill()
    t.penup()
#Author: Mai Huu Nghia
def draw_hcmut5():
    t.setposition(-130,32)
    t.pendown()
    t.begin_fill()
    t.color("white")
    t.pensize (10)
    t.pencolor("white")
    #t.left(180)
    t.forward(149)
    t.right(60)
    t.forward(149)
    t.right(60)
    t.forward(154)
    t.right(60)
    t.forward(149)
    t.right(60)
    t.forward(149)
    t.right(60)
    t.forward(154)
    t.end_fill()
    t.penup()
#Author: Mai Huu Nghia
def write_BK():
    turtle.pencolor('white')
    turtle.setposition(-100.0,-100.0)
    turtle.color('#042B92')
    style = ('Sans-serif', 100, 'bold')
    turtle.write('BK', font=style)
    turtle.hideturtle()
#Author: Mai Huu Nghia
def write_TPHCM():
    turtle.pencolor('white')
    turtle.setposition(-100.0,-130.0)
    turtle.color('#1387DB')
    style = ('Sans-serif', 38, 'bold')
    turtle.write('TP.HCM', font=style)
    turtle.hideturtle()
#Author: Mai Huu Nghia
draw_hcmut1()
draw_hcmut2()
draw_hcmut3()
draw_hcmut4()
draw_hcmut5()
write_BK()
write_TPHCM()

t.hideturtle
turtle.done()